version: 2

updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: vimeo/psalm
    versions:
    - 4.4.0
    - 4.5.0
    - 4.6.0
